- docker-compose.yml
I encountered a permission issue trying to launch fuseki with my fedora machine. The container did not have the rights to access the data directory.
Exposing the volume without the `z` parameter seems to break things in SELinux. See: https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker
> fix: docker volume mount permission issue

- .git-hooks/post-commit
- .git-hooks/pre-commit
- .prettierignore
- .prettierrc.json
- package.json
You might have to re-install or run `git config core.hooksPath .git-hooks` manually in existing repositories.
This way, the prettier is run over all staged files. The prettified files are committed.
> Make prettier run automatically before commit

- website/src/components/widgets/Developers.astro
Add link to the activitypods github repository instead of the existing one (possibly the default of the template used for the website?)
> Fix link to github repo

- packages/announcer/service.js
- packages/events/services/event.js
- packages/events/services/status.js
Depends on https://github.com/assemblee-virtuelle/semapps/pull/1164
The SemApps PR is a **breaking change** since a service action is moved. Here, the calls are adjusted to the new action name.
> Chore/refactor (BREAKING) await create complete

- app-boilerplate/backend/.env
- app-boilerplate/backend/.gitignore
- app-boilerplate/backend/config/config.js
- app-boilerplate/backend/moleculer.config.js
- app-boilerplate/backend/package.json
- app-boilerplate/backend/services/app.service.js
- app-boilerplate/backend/services/auth-account.service.js
- app-boilerplate/backend/services/core.service.js
- package.json
- packages/app/LICENSE
- packages/app/config/context.json
- packages/app/index.js
- packages/app/package.json
- packages/app/service.js
- packages/app/services/access-needs-groups.js
- packages/app/services/access-needs.js
- packages/app/services/actors.js
- tests/app-registration.test.js
- tests/apps/example.app.js
- tests/initialize.js
- tests/package.json
- yarn.lock
Close #92
- Setup a boilerplate with an application declaring its AccessNeeds
- Add tests
> Application AccessNeeds declaration

- app-boilerplate/backend/services/app.service.js
- packages/app/package.json
- packages/app/service.js
- packages/app/services/access-grants.js
- packages/app/services/access-needs-groups.js
- packages/app/services/actors.js
- packages/app/services/app-registrations.js
- packages/app/services/data-grants.js
- packages/app/services/registration.js
- packages/core/config/context-interop.json
- packages/core/services/installation/index.js
- packages/core/services/installation/sub-services/access-grants.js
- packages/core/services/installation/sub-services/app-registrations.js
- packages/core/services/installation/sub-services/data-grants.js
- tests/app-installation.test.js
- tests/apps/example.app.js
- tests/initialize.js
Close #101 
- Prevent to install app if it is already installed
- Handle `Undo > apods:Install` activities sent to the outbox
- On uninstall, delete app registration (and associated grants) 
- Warn app with a `Delete > interop:ApplicationRegistration` activity
- On reception, app delete the cached app registration (and associated grants)
- Refactor existing code
- Add new tests
> App uninstall

- README.md
- frontend/.gitignore
- frontend/package.json
- frontend/yarn.lock
Requires https://github.com/assemblee-virtuelle/semapps/pull/1181
- Use `yalc link` instead of `yarn link`
- For unlink, use `yarn remove` and manually delete the folders in `node_modules` before doing a reinstall (this is necessary, see [this issue](https://github.com/wclr/yalc/issues/127))
> Use Yalc instead of yarn link

- README.md
- deploy/backend/Dockerfile
- package.json
The functionaliy is now handled by `yarn` or `yarn install`.
> Chore: remove deprecated lerna bootstrap commands

- frontend/.eslintrc.json
- frontend/package.json
- frontend/src/index.js
- frontend/yarn.lock
* add typescript as devDependency for frontend (worked while testing, since it was still present in my `node_modules` dir)
* resolve issue with duplicate react router dependency
* prevent react-scripts from erroring on eslint issues
* use react18's method `createRoot` instead of `ReactDOM.render`
> Fix: fix frontend dependencies

- website/src/layouts/BaseLayout.astro
This allows feed readers and browser extensions to discover it.
> Expose RSS feed in meta tags

- .gitignore
- README.md
Just some suggested wording tweaks to the main README (and adding IntelliJ project files to the `.gitignore`).
> add IntelliJ project files to gitignore, tweak README wording

- packages/announcer/service.js
- packages/app/service.js
- packages/app/services/pod-handling/pod-containers.js
- packages/app/services/pod-handling/pod-notification.js
- packages/app/services/pod-handling/pod-resources.js
- packages/core/service.js
- packages/core/services/installation/sub-services/data-grants.js
- packages/core/services/mail-notifications.js
- packages/ontologies/index.js
- packages/ontologies/solid.json
- packages/solid-notifications/services/provider/sub-services/webhook.js
- packages/type-index/LICENSE
- packages/type-index/index.js
- packages/type-index/package.json
- packages/type-index/services/type-indexes.js
- packages/type-index/services/type-registrations.js
- tests/pods-creation.test.js
> Requires https://github.com/assemblee-virtuelle/semapps/pull/1275
I started adapting the LdpRegistryService to handle the diversity of containers in Pods, but this is difficult to maintain, non-standard, and external apps don't have access to this in-memory information. Switching to TypeIndex solve many problems.
Notes:
- We will add a more complete TypeIndex support (also on the frontend) if we get the new NLnet grant submission.
- We have created a `pod-containers.getByType` action to find a container using TypeIndexes. It is not used at the moment.
- We have kept the `apods:registeredContainer` predicate in DataGrants since it is the fastest way for apps to find about containers
- Later we will probably create a @semapps/solid package with the notifications and type index features. …
> Basic TypeIndex implementation

- frontend/.env
- frontend/src/config/dataServers.js
- frontend/src/pages/ChoosePodProviderPage/ChoosePodProviderPage.tsx
- frontend/src/resources/TrustedApp.js
- frontend/src/utils.ts
- Load data from https://activitypods.org/data/pod-providers
- Use new `apods:baseUrl` predicate which replace `apods:domainName`
> ChoosePodProvidersPage: use new Pod providers lists

- frontend/src/App.js
- frontend/src/pages/ApplicationsPage/InstalledApps.js
- frontend/src/pages/AuthorizePage/AuthorizePageView.js
- frontend/src/pages/ProfileCreatePage/ProfileCreatePage.js
- packages/app/services/registration/registration.js
- packages/core/services/installation/sub-services/access-grants.js
- packages/core/services/installation/sub-services/app-registrations.js
- packages/core/services/installation/sub-services/data-grants.js
- packages/core/services/jwk.js
- packages/core/services/oidc-provider/base-config.js
- packages/core/services/oidc-provider/oidc-provider.js
Closes https://github.com/activitypods/activitypods/issues/270 
Closes #259
Requires https://github.com/assemblee-virtuelle/semapps/pull/1295 and https://github.com/assemblee-virtuelle/semapps/pull/1297 
- Wait for `Accept` activity from app on install and uninstall
- Fix node-oidc-provider Grant issue by letting it redirect to /authorize screen
- On app uninstall, remove the corresponding Grant so that the /authorize screen is shown again if the app is installed again
- If login is expired, remove the token and go to the login screen
- Increase ID token TTL to one year (this will be changed when we complete Solid-OIDC)
- Add some documentation on how we configured the OIDC provider
> Improve app installation flow

- packages/app/mappings.js
- packages/app/service.js
- packages/app/services/registration/access-description-sets.js
- packages/app/services/registration/access-grants.js
- packages/app/services/registration/access-needs-groups.js
- packages/app/services/registration/access-needs.js
- packages/app/services/registration/actors.js
- packages/app/services/registration/app-registrations.js
- packages/app/services/registration/class-descriptions.js
- packages/app/services/registration/data-grants.js
- packages/app/services/registration/registration.js
- packages/app/utils.js
- packages/ontologies/oidc.json
First step toward app upgrade (https://github.com/activitypods/activitypods/issues/102)
When the app settings change:
- Update Application resource
- Update AccessNeed and AccessNeedGroups resources
- Update ClassDescription and AccessDescriptionSet resources
Since all these resources (except the Application) are immutable, changing any of them will necessarily create new URIs, and it will reflect on the Application resource. Looking at the `dc:modified` predicate will thus be a simple way to identity when an application has been changed.
> Update app, access needs and class descriptions when settings change

- pod-provider/backend/services/core/keys.js
For new setups, we don't need the directory and setting anymore.
If I understand correctly, there are no legacy configurations using the refactored pod-provider setup, right @srosset81?
Depends on https://github.com/assemblee-virtuelle/semapps/pull/1315
> chore: remove legacy `actorsKeyPairDir` setting from key service

- docs/src/content/docs/app-framework/backend/application-registration.md
I have noticed this broken link, but there are probably more. You may consider using [markdownlint](https://github.com/DavidAnson/markdownlint) with the [markdownlint-rule-relative-links](https://github.com/theoludwig/markdownlint-rule-relative-links) rule to avoid this in the future.
> Fix broken link

- app-framework/react/src/components/LoginPage.tsx
- app-framework/react/src/hooks/useRegisterApp.ts
- app-framework/react/src/messages/en.ts
Hello everyone,
this is my first contribution here :)
I tested it locally and it showed me the error notification, after I removed the interop:hasAuthorizationAgent triple from the dataset manually in my local setup. 
The relevant translation strings seem to be maintained in another project (semapps/auth-provider), where I will link the according PR here.
closes #394
> Show user error notification, if user authorization agent not found

- docs/src/content/docs/architecture/authentication.md
Just noticed this whilst reading the docs: 
It's clearly not formatted correctly, so this removes the extra backtick and fixes that.
> Docs: Fix accidental double backtick in authentication.md

- pod-provider/backend/yarn.lock
Prevented pod provider from running.
Replaces the yarml.lock file with the one from branch `3.0` (which as the same package.json dependencies).
> fix: pod-provider dependency issue (solid oidc>koa>is-generator-function)
